import { genAI, getTextModelName } from '@/lib/ai/gemini';
import { getGeminiConfig } from '@/lib/firebase/config/environments';
import { db } from '@/lib/firebase/firebase';
import { collection, doc, getDoc, setDoc } from 'firebase/firestore';

/**
 * Content Opportunity
 * A unique content idea generated by AI
 */
export interface ContentOpportunity {
  id: string; // Unique identifier
  title: string; // Short title (e.g., "Festive Traditional Look")
  description: string; // What this opportunity is about
  tags: string[]; // Searchable tags
  isViral?: boolean; // Is this a trending/viral topic?
  relevanceScore: number; // 0-10, how relevant today
}

/**
 * Daily Context Interface
 * Contains information about what's special/relevant today
 */
export interface DailyContext {
  date: string; // YYYY-MM-DD
  summary: string; // Brief summary of today
  contentOpportunities: ContentOpportunity[]; // 15-20 unique content ideas
  trendingTopics: string[]; // What's viral/trending today
  festivals: string[]; // Hindu festivals, global holidays
  specialEvents: string[]; // National days, observances
  season: string; // Current season
  seasonalThemes: string[]; // Seasonal activities
  locationContext?: string; // India-specific context
  generatedAt: string; // ISO timestamp
}

/**
 * Daily Context Service
 * Fetches and caches daily context information using Gemini AI
 */
export const DailyContextService = {
  /**
   * Get today's context (with caching)
   * @returns Daily context information
   */
  getTodaysContext: async (): Promise<DailyContext> => {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    
    // Try to get cached context from Firestore
    const cached = await DailyContextService.getCachedContext(today);
    if (cached) {
      console.log('✅ Using cached daily context for:', today);
      return cached;
    }
    
    // Generate new context using Gemini
    console.log('🔄 Generating new daily context for:', today);
    const context = await DailyContextService.generateContext(today);
    
    // Cache for future use
    await DailyContextService.cacheContext(context);
    
    return context;
  },

  /**
   * Get cached context from Firestore
   * @param date - Date string (YYYY-MM-DD)
   * @returns Cached context or null
   */
  getCachedContext: async (date: string): Promise<DailyContext | null> => {
    try {
      const docRef = doc(db, 'daily_context', date);
      const docSnap = await getDoc(docRef);
      
      if (docSnap.exists()) {
        return docSnap.data() as DailyContext;
      }
      
      return null;
    } catch (error) {
      console.error('Failed to get cached context:', error);
      return null;
    }
  },

  /**
   * Cache context to Firestore
   * @param context - Daily context to cache
   */
  cacheContext: async (context: DailyContext): Promise<void> => {
    try {
      const docRef = doc(db, 'daily_context', context.date);
      await setDoc(docRef, context);
      console.log('✅ Cached daily context for:', context.date);
    } catch (error) {
      console.error('Failed to cache context:', error);
    }
  },

  /**
   * Generate context using Gemini AI
   * @param date - Date string (YYYY-MM-DD)
   * @returns Generated context
   */
  generateContext: async (date: string): Promise<DailyContext> => {
    const modelName = getTextModelName();

    const dateObj = new Date(date);
    const formattedDate = dateObj.toLocaleDateString('en-IN', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const prompt = `Today is ${formattedDate} in India. Analyze what's special about today and provide DYNAMIC, CREATIVE content opportunities for Instagram posting.

Your task: Generate 15-20 UNIQUE, SPECIFIC content ideas that are relevant today. Be creative and unexpected!

Consider ALL of these:
1. Hindu festivals and religious celebrations
2. National holidays and observances in India
3. International days and global events
4. Current season and seasonal themes (monsoon, summer, winter, festival season)
5. Popular cultural activities (travel, celebrations, family gatherings)
6. TRENDING TOPICS - what's viral/popular right now (general trends, not news)
7. Lifestyle themes (fitness, fashion, beauty, food, home decor)
8. Creative angles (behind-the-scenes, day-in-life, transformation, tips)
9. DIVERSE locations across India (NOT just Goa/beaches - include cities, heritage sites, mountains, markets, cafes, homes)

CRITICAL: Generate DIVERSE opportunities - mix festivals with lifestyle, trending with seasonal, traditional with modern.

Respond in JSON format ONLY (no markdown, no code blocks):
{
  "summary": "Brief 1-sentence summary of today",
  "festivals": ["Festival names if any"],
  "specialEvents": ["Event names if any"],
  "season": "Current season name",
  "seasonalThemes": ["Seasonal activities"],
  "trendingTopics": ["What's trending/viral now - be specific"],
  "locationContext": "What's happening in India today",
  "contentOpportunities": [
    {
      "id": "unique-id-1",
      "title": "Short catchy title",
      "description": "What this content idea is about",
      "tags": ["tag1", "tag2", "tag3"],
      "isViral": true/false,
      "relevanceScore": 8
    }
  ]
}

IMPORTANT for contentOpportunities:
- Generate 15-20 ideas minimum
- Mix categories: 3-4 festival/event, 3-4 seasonal, 2-3 trending, 3-4 lifestyle, 2-3 creative angles
- Be SPECIFIC (not "traditional look" but "Karwa Chauth moon-gazing traditional styling")
- Include modern twists on traditional themes
- Add unexpected creative ideas
- Mark viral/trending topics with isViral: true
- Score relevance 1-10 based on today's context
- EMPHASIZE diverse Indian settings (urban cafes, heritage sites, local markets, rooftop gardens, home interiors, NOT just beaches/Goa)
- Focus on REALISTIC, achievable photo scenarios

Example opportunities (for reference, generate NEW ones):
- "Monsoon street fashion styling"
- "Festive home decoration DIY"
- "Weekend brunch aesthetic goals"
- "Late night city exploration vibes"
- "Heritage walk heritage styling"
- "Cozy home reading corner"
- "Local market shopping vibes"

Generate the JSON now:`;

    try {
      const result = await genAI.models.generateContent({
        model: modelName,
        contents: prompt,
      });
      const responseText = result.candidates?.[0]?.content?.parts?.[0]?.text || '';
      
      // Parse the JSON response
      let parsedResponse;
      try {
        // Remove markdown code blocks if present
        const cleanResponse = responseText
          .replace(/```json\n?/g, '')
          .replace(/```\n?/g, '')
          .trim();
        parsedResponse = JSON.parse(cleanResponse);
      } catch (parseError) {
        console.error('Failed to parse Gemini response:', responseText);
        // Return default context if parsing fails
        parsedResponse = {
          summary: 'Regular day',
          festivals: [],
          specialEvents: [],
          season: 'General',
          seasonalThemes: ['daily life', 'lifestyle'],
          trendingTopics: ['lifestyle content', 'daily vlogs'],
          locationContext: 'Regular day',
          contentOpportunities: DailyContextService.getDefaultOpportunities()
        };
      }

      const context: DailyContext = {
        date,
        summary: parsedResponse.summary || 'Regular day',
        festivals: parsedResponse.festivals || [],
        specialEvents: parsedResponse.specialEvents || [],
        season: parsedResponse.season || 'General',
        seasonalThemes: parsedResponse.seasonalThemes || [],
        trendingTopics: parsedResponse.trendingTopics || [],
        contentOpportunities: parsedResponse.contentOpportunities || DailyContextService.getDefaultOpportunities(),
        locationContext: parsedResponse.locationContext,
        generatedAt: new Date().toISOString()
      };

      console.log('✅ Generated daily context:', context);
      return context;
    } catch (error) {
      console.error('Failed to generate context with Gemini:', error);
      
      // Return default context on error
      return {
        date,
        summary: 'Regular day - API error',
        festivals: [],
        specialEvents: [],
        season: 'General',
        seasonalThemes: ['daily life', 'lifestyle'],
        trendingTopics: ['lifestyle content'],
        contentOpportunities: DailyContextService.getDefaultOpportunities(),
        generatedAt: new Date().toISOString()
      };
    }
  },

  /**
   * Get default content opportunities (fallback)
   */
  getDefaultOpportunities: (): ContentOpportunity[] => {
    return [
      {
        id: 'default-lifestyle-1',
        title: 'Casual Daily Look',
        description: 'Comfortable everyday styling with relaxed vibes',
        tags: ['lifestyle', 'casual', 'daily'],
        relevanceScore: 5
      },
      {
        id: 'default-fashion-1',
        title: 'Chic Street Fashion',
        description: 'Modern urban fashion with contemporary aesthetics',
        tags: ['fashion', 'street-style', 'modern'],
        relevanceScore: 6
      },
      {
        id: 'default-seasonal-1',
        title: 'Cozy Home Vibes',
        description: 'Relaxed home setting with warm comfortable atmosphere',
        tags: ['lifestyle', 'cozy', 'home'],
        relevanceScore: 5
      },
      {
        id: 'default-outdoor-1',
        title: 'Outdoor Natural Setting',
        description: 'Fresh outdoor environment with natural lighting',
        tags: ['outdoor', 'nature', 'fresh'],
        relevanceScore: 5
      },
      {
        id: 'default-evening-1',
        title: 'Evening Elegance',
        description: 'Elegant evening look with sophisticated styling',
        tags: ['evening', 'elegant', 'classy'],
        relevanceScore: 5
      }
    ];
  },

  /**
   * Get context summary text
   * @param context - Daily context
   * @returns Human-readable summary
   */
  getContextSummary: (context: DailyContext): string => {
    const parts: string[] = [];
    
    parts.push(context.summary);
    
    if (context.festivals.length > 0) {
      parts.push(`Festivals: ${context.festivals.join(', ')}`);
    }
    
    if (context.specialEvents.length > 0) {
      parts.push(`Events: ${context.specialEvents.join(', ')}`);
    }
    
    if (context.contentOpportunities.length > 0) {
      const topOpportunities = context.contentOpportunities
        .sort((a, b) => b.relevanceScore - a.relevanceScore)
        .slice(0, 3)
        .map(o => o.title);
      parts.push(`Top Ideas: ${topOpportunities.join(', ')}`);
    }
    
    return parts.join(' | ');
  }
};
