import { genAI, getTextModelName } from '@/lib/ai/gemini';
import { getGeminiConfig } from '@/lib/firebase/config/environments';
import { db } from '@/lib/firebase/firebase';
import { collection, doc, getDoc, setDoc } from 'firebase/firestore';

/**
 * Content Opportunity
 * A unique content idea generated by AI
 */
export interface ContentOpportunity {
  id: string; // Unique identifier
  title: string; // Short title (e.g., "Festive Traditional Look")
  description: string; // What this opportunity is about
  tags: string[]; // Searchable tags
  isViral?: boolean; // Is this a trending/viral topic?
  relevanceScore: number; // 0-10, how relevant today
}

/**
 * Daily Context Interface
 * Contains information about what's special/relevant today
 */
export interface DailyContext {
  date: string; // YYYY-MM-DD
  summary: string; // Brief summary of today
  contentOpportunities: ContentOpportunity[]; // 15-20 unique content ideas
  trendingTopics: string[]; // What's viral/trending today
  festivals: string[]; // Hindu festivals, global holidays
  specialEvents: string[]; // National days, observances
  season: string; // Current season
  seasonalThemes: string[]; // Seasonal activities
  locationContext?: string; // India-specific context
  generatedAt: string; // ISO timestamp
}

/**
 * Daily Context Service
 * Fetches and caches daily context information using Gemini AI
 */
export const DailyContextService = {
  /**
   * Get today's context (with caching)
   * @returns Daily context information
   */
  getTodaysContext: async (): Promise<DailyContext> => {
    const today = new Date().toISOString().split('T')[0]; // YYYY-MM-DD
    
    // Try to get cached context from Firestore
    const cached = await DailyContextService.getCachedContext(today);
    if (cached) {
      console.log('✅ Using cached daily context for:', today);
      return cached;
    }
    
    // Generate new context using Gemini
    console.log('🔄 Generating new daily context for:', today);
    const context = await DailyContextService.generateContext(today);
    
    // Cache for future use
    await DailyContextService.cacheContext(context);
    
    return context;
  },

  /**
   * Get cached context from Firestore
   * @param date - Date string (YYYY-MM-DD)
   * @returns Cached context or null
   */
  getCachedContext: async (date: string): Promise<DailyContext | null> => {
    try {
      const docRef = doc(db, 'daily_context', date);
      const docSnap = await getDoc(docRef);
      
      if (docSnap.exists()) {
        return docSnap.data() as DailyContext;
      }
      
      return null;
    } catch (error) {
      console.error('Failed to get cached context:', error);
      return null;
    }
  },

  /**
   * Cache context to Firestore
   * @param context - Daily context to cache
   */
  cacheContext: async (context: DailyContext): Promise<void> => {
    try {
      const docRef = doc(db, 'daily_context', context.date);
      await setDoc(docRef, context);
      console.log('✅ Cached daily context for:', context.date);
    } catch (error) {
      console.error('Failed to cache context:', error);
    }
  },

  /**
   * Generate context using Gemini AI
   * @param date - Date string (YYYY-MM-DD)
   * @returns Generated context
   */
  generateContext: async (date: string): Promise<DailyContext> => {
    const modelName = getTextModelName();

    const dateObj = new Date(date);
    const formattedDate = dateObj.toLocaleDateString('en-IN', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const prompt = `Today is ${formattedDate}. Analyze what's special about today and provide DYNAMIC, CREATIVE content opportunities for visual storytelling and photography.

Your task: Generate 15-20 UNIQUE, SPECIFIC content ideas that are relevant today. Be creative, diverse, and unexpected!

Consider ALL of these categories:
1. Religious/cultural celebrations and festivals (if any today)
2. National/international holidays and observances
3. Current season and seasonal themes
4. Popular cultural activities and lifestyle trends
5. TRENDING TOPICS - what's viral/popular right now (general trends, not news)
6. Lifestyle themes (wellness, fashion, beauty, food, home, hobbies)
7. Creative photography angles (golden hour, atmospheric, candid, artistic)
8. Diverse settings and locations (urban, nature, indoor, cultural, modern)
9. Time-of-day specific opportunities (morning energy, afternoon casual, evening ambiance)
10. Mood-based concepts (peaceful, energetic, elegant, playful, dramatic)

CRITICAL REQUIREMENTS:
- Generate DIVERSE opportunities across multiple categories
- Mix traditional with modern, formal with casual, indoor with outdoor
- Be SPECIFIC and VISUAL (describe scenes that can be photographed)
- Avoid clichés and overused concepts
- Focus on REALISTIC, achievable scenarios
- Each opportunity should inspire a unique photo/video

Respond in JSON format ONLY (no markdown, no code blocks):
{
  "summary": "Brief 1-sentence summary of today",
  "festivals": ["Festival/celebration names if any"],
  "specialEvents": ["Observance names if any"],
  "season": "Current season name",
  "seasonalThemes": ["Seasonal activities"],
  "trendingTopics": ["What's trending/viral - be specific"],
  "locationContext": "General context about today",
  "contentOpportunities": [
    {
      "id": "unique-id-1",
      "title": "Short catchy title (3-5 words)",
      "description": "Specific visual description of this content opportunity",
      "tags": ["category", "mood", "style"],
      "isViral": true/false,
      "relevanceScore": 1-10
    }
  ]
}

IMPORTANT for contentOpportunities:
- Generate 15-20 diverse ideas minimum
- Mix categories: festivals/events, seasonal, trending, lifestyle, creative, mood-based
- Be SPECIFIC with visuals (not "casual look" but "cozy knit sweater by window with morning coffee")
- Include lighting descriptions (golden hour, soft natural light, dramatic shadows)
- Specify settings clearly (rooftop cafe, library corner, urban street, home kitchen)
- Mark truly trending/viral topics with isViral: true
- Score relevance 1-10 based on today's actual relevance
- Focus on PHOTOGENIC, visually interesting scenarios

Generate creative, specific opportunities now:`;

    try {
      const result = await genAI.models.generateContent({
        model: modelName,
        contents: prompt,
      });
      const responseText = result.candidates?.[0]?.content?.parts?.[0]?.text || '';
      
      // Parse the JSON response
      let parsedResponse;
      try {
        // Remove markdown code blocks if present
        const cleanResponse = responseText
          .replace(/```json\n?/g, '')
          .replace(/```\n?/g, '')
          .trim();
        parsedResponse = JSON.parse(cleanResponse);
      } catch (parseError) {
        console.error('Failed to parse Gemini response:', responseText);
        // Return default context if parsing fails
        parsedResponse = {
          summary: 'Regular day',
          festivals: [],
          specialEvents: [],
          season: 'General',
          seasonalThemes: ['daily life', 'lifestyle'],
          trendingTopics: ['lifestyle content', 'daily vlogs'],
          locationContext: 'Regular day',
          contentOpportunities: DailyContextService.getDefaultOpportunities()
        };
      }

      const context: DailyContext = {
        date,
        summary: parsedResponse.summary || 'Regular day',
        festivals: parsedResponse.festivals || [],
        specialEvents: parsedResponse.specialEvents || [],
        season: parsedResponse.season || 'General',
        seasonalThemes: parsedResponse.seasonalThemes || [],
        trendingTopics: parsedResponse.trendingTopics || [],
        contentOpportunities: parsedResponse.contentOpportunities || DailyContextService.getDefaultOpportunities(),
        locationContext: parsedResponse.locationContext,
        generatedAt: new Date().toISOString()
      };

      console.log('✅ Generated daily context:', context);
      return context;
    } catch (error) {
      console.error('Failed to generate context with Gemini:', error);
      
      // Return default context on error
      return {
        date,
        summary: 'Regular day - API error',
        festivals: [],
        specialEvents: [],
        season: 'General',
        seasonalThemes: ['daily life', 'lifestyle'],
        trendingTopics: ['lifestyle content'],
        contentOpportunities: DailyContextService.getDefaultOpportunities(),
        generatedAt: new Date().toISOString()
      };
    }
  },

  /**
   * Get default content opportunities (fallback)
   * Generates dynamic opportunities even when AI fails
   */
  getDefaultOpportunities: (): ContentOpportunity[] => {
    const timeOfDay = new Date().getHours();
    const currentMonth = new Date().getMonth(); // 0-11
    
    // Dynamic based on time
    const timeBasedOpportunity = timeOfDay < 12 
      ? {
          id: 'dynamic-morning',
          title: 'Fresh Morning Energy',
          description: 'Capture the freshness of morning with natural light and vibrant energy',
          tags: ['morning', 'fresh', 'energetic'],
          relevanceScore: 7
        }
      : timeOfDay < 17
      ? {
          id: 'dynamic-afternoon',
          title: 'Afternoon Lifestyle',
          description: 'Natural daylight photography with authentic everyday moments',
          tags: ['afternoon', 'lifestyle', 'natural'],
          relevanceScore: 6
        }
      : {
          id: 'dynamic-evening',
          title: 'Golden Hour Magic',
          description: 'Warm evening light creating stunning visual atmosphere',
          tags: ['evening', 'golden-hour', 'warm'],
          relevanceScore: 8
        };

    // Dynamic based on season
    const seasonalOpportunity = currentMonth >= 2 && currentMonth <= 5
      ? {
          id: 'dynamic-spring-summer',
          title: 'Bright Outdoor Setting',
          description: 'Utilize natural outdoor environments with bright cheerful vibes',
          tags: ['outdoor', 'bright', 'cheerful'],
          relevanceScore: 7
        }
      : currentMonth >= 6 && currentMonth <= 9
      ? {
          id: 'dynamic-monsoon-autumn',
          title: 'Cozy Indoor Atmosphere',
          description: 'Warm indoor settings with comfortable relaxed mood',
          tags: ['indoor', 'cozy', 'comfortable'],
          relevanceScore: 6
        }
      : {
          id: 'dynamic-winter',
          title: 'Elegant Indoor Styling',
          description: 'Sophisticated indoor photography with elegant ambiance',
          tags: ['indoor', 'elegant', 'sophisticated'],
          relevanceScore: 7
        };

    return [
      timeBasedOpportunity,
      seasonalOpportunity,
      {
        id: 'dynamic-lifestyle-1',
        title: 'Authentic Lifestyle Moment',
        description: 'Capture genuine everyday moments with natural expressions',
        tags: ['lifestyle', 'authentic', 'candid'],
        relevanceScore: 6
      },
      {
        id: 'dynamic-fashion-1',
        title: 'Contemporary Style Story',
        description: 'Modern fashion photography with clean aesthetic',
        tags: ['fashion', 'modern', 'stylish'],
        relevanceScore: 6
      },
      {
        id: 'dynamic-mood-1',
        title: 'Artistic Expression',
        description: 'Creative photography with artistic composition and mood',
        tags: ['artistic', 'creative', 'expressive'],
        relevanceScore: 5
      }
    ];
  },

  /**
   * Get context summary text
   * @param context - Daily context
   * @returns Human-readable summary
   */
  getContextSummary: (context: DailyContext): string => {
    const parts: string[] = [];
    
    parts.push(context.summary);
    
    if (context.festivals.length > 0) {
      parts.push(`Festivals: ${context.festivals.join(', ')}`);
    }
    
    if (context.specialEvents.length > 0) {
      parts.push(`Events: ${context.specialEvents.join(', ')}`);
    }
    
    if (context.contentOpportunities.length > 0) {
      const topOpportunities = context.contentOpportunities
        .sort((a, b) => b.relevanceScore - a.relevanceScore)
        .slice(0, 3)
        .map(o => o.title);
      parts.push(`Top Ideas: ${topOpportunities.join(', ')}`);
    }
    
    return parts.join(' | ');
  }
};
